### ISSUE TITLE
Examples for running on ubuntu 20.04?

### ISSUE THREAD

**Issue by Shadowblitz16** [MichalStrehovsky/zerosharp#12]
Is there a example for ubuntu 20.04?

**Comment by MichalStrehovsky** [comment]
https://github.com/MichalStrehovsky/zerosharp/commit/26b8800c63f2ddbbfc1927861299008a59f916d9 now has the no-runtime sample that works on Linux.

**Comment by Shadowblitz16** [comment]
@MichalStrehovsky I mean for baremetal

**Comment by Shadowblitz16** [comment]
> [26b8800](https://github.com/MichalStrehovsky/zerosharp/commit/26b8800c63f2ddbbfc1927861299008a59f916d9) now has the no-runtime sample that works on Linux.

your csproj literally blocks if it's not WindowsNT

**Comment by Shadowblitz16** [comment]
@MichalStrehovsky please reopen this...
Your csproj file also looks like it uses windows only commands.
```
create vdisk file=$(VHDFilePath) maximum=500
select vdisk file=$(VHDFilePath)
attach vdisk
convert gpt
create partition efi size=100
format quick fs=fat32 label="System"
assign letter=X
      </AttachVHDLines>
      <DetachVHDLines>
select vdisk file=$(VHDFilePath)
select partition 2
remove letter=X
detach vdisk
```

**Comment by MichalStrehovsky** [comment]
I recommend looking here instead: https://github.com/bflattened/bflat/tree/master/samples/Snake
