### ISSUE TITLE
Is it possible to integrate the build with the solution rather then using a cmd file for .net 5?

### ISSUE THREAD

**Issue by Shadowblitz16** [MichalStrehovsky/zerosharp#13]
Is it possible to integrate the build with the solution rather then using a cmd file for .net 5?
![image](https://user-images.githubusercontent.com/2453707/123354538-bd7dc600-d518-11eb-9835-e6e374e6785b.png)

**Comment by MichalStrehovsky** [comment]
Yes, https://github.com/MichalStrehovsky/zerosharp/commit/26b8800c63f2ddbbfc1927861299008a59f916d9 made it so that we have csproj files for these.
