### ISSUE TITLE
with-runtime no longer work

### ISSUE THREAD

**Issue by kant2002** [MichalStrehovsky/zerosharp#2]
I try to play with that repository. EFI example most fun 😄 . Other examples is interesting as well.

I experience issue with `with-runtime` project which does not work. I believe to make it work it is required to update binaries, but better it is handled not by me.

**Comment by MichalStrehovsky** [comment]
Yeah, that demo is rather fragile. Building Test.CoreLib out of CoreRT repo and placing it there is the best course of action for now.
