### ISSUE TITLE
%DROPPATH% doesn't exist

### ISSUE THREAD

**Issue by jwoff78** [MichalStrehovsky/zerosharp#21]
I cannot find droppath anywhere on system or any guides on how to find droppath at all.

**Comment by MichalStrehovsky** [comment]
The scripts are for advanced use ("Some samples also come with a shell script (*.cmd) that pieces together all the tools and avoid MSBuild or dotnet. You need to make sure you have environment set up before running the script. Look at the script for details. The script is redundant with the *.csproj project files."). DROPPATH is where ILCompiler package is.
