### ISSUE TITLE
Dynamically linking against C library

### ISSUE THREAD

**Issue by MAG-MichaelK** [MichalStrehovsky/zerosharp#49]
In the readme, it is mentioned that most of the size of the `with-runtime` example comes from the C library. Is it possible to instruct NativeAOT to dynamically link against msvcrt on Windows instead of statically linking it?

**Comment by MAG-MichaelK** [comment]
> it was linking dynamically everywhere else for a while

So is it no longer doing that, or is it indeed dynamically linking on all platforms now?

**Comment by MichalStrehovsky** [comment]
Dynamic to ucrt on windows and dynamic to glibc/musl on linux
