### ISSUE TITLE
None of the samples work

### ISSUE THREAD

**Issue by netcorefan1** [MichalStrehovsky/zerosharp#9]
I have no idea why! 
- runtime.win-x64.microsoft.dotnet.ilcompiler\6.0.0-preview.2.21107.2
- Latest Visual Studio 2019 with latest SDK and C++
Am I missing something obvious?

https://user-images.githubusercontent.com/63934725/107170344-5d9ade80-69c0-11eb-9bbb-6152c9fa16e4.mp4

**Comment by MichalStrehovsky** [comment]
```
error CS2001: Source file 'D:\VsIDE\zerosharp.cs could not be found
```

You need to set the directory where zerosharp.cs is as the current directory. The build scripts assume current directory is where the script is.

**Comment by MichalStrehovsky** [comment]
Oh, I see. The TentativeInstanceMethod thing.

I broke this last week in the NativeAOT repo. I'll fix it shorty.

**Comment by MichalStrehovsky** [comment]
Roll back the compiler to 6.0.0-alpha.1.21055.3 in the meantime.

**Comment by netcorefan1** [comment]
Thanks for your help. I can't find any change in the repo. Did you published the fix elsewhere?

**Comment by MichalStrehovsky** [comment]
Sorry I had another pull request out that would conflict. I submitted the fix now. A NuGet package with the fix should be out within 24 hours or so.
